packages:
  - 'packages/*'
  - 'docs'
allowBuilds:
  esbuild: false
  unrs-resolver: false
  vue-demi: false
patchedDependencies:
  '@nuxt/nitro-server@4.5.2': patches/@nuxt__nitro-server@4.5.2.patch
  nuxt@4.5.2: patches/nuxt@4.5.2.patch
  overlayscrollbars@2.16.0: patches/overlayscrollbars@2.16.0.patch
