export { cn } from './lib/cn'
export { tv } from './lib/tv'
export type { VariantProps } from './lib/tv'

export { EASE, DURATION, TRAVEL, STAGGER, TRANSITION, cssEase } from './motion'
export type { Bezier, TransitionName } from './motion'

export { provideUiLocale, useUiLocale, zhCN, enUS } from './locale'
export type { UiMessages, PartialUiMessages } from './locale'

export { REQUIRED_SINGLETONS } from './singletons'
export type { RequiredSingleton } from './singletons'

export { default as Button } from './components/button/Button.vue'
export type { ButtonVariants } from './components/button/button.variants'
export { default as Ripple } from './components/ripple/Ripple.vue'
export { default as Input } from './components/input/Input.vue'
export type { InputVariants } from './components/input/input.variants'
export { default as Card } from './components/card/Card.vue'
export type { CardVariants } from './components/card/card.variants'
export { default as VisuallyHidden } from './components/visually-hidden/VisuallyHidden.vue'
export { default as Text } from './components/text/Text.vue'
export type { TextVariants } from './components/text/text.variants'
export { default as Heading } from './components/heading/Heading.vue'
export type { HeadingVariants } from './components/heading/heading.variants'
export { default as Spinner } from './components/spinner/Spinner.vue'
export { default as ScrollArea } from './components/scroll-area/ScrollArea.vue'
