export { injectTabsRootContext, type TabsRootContext } from './context'
export { TabsContent, type TabsContentProps } from './TabsContent'
export { TabsList, type TabsListProps } from './TabsList'
export { TabsRoot, type TabsRootEmits, type TabsRootProps } from './TabsRoot'
export { TabsTrigger, type TabsTriggerProps } from './TabsTrigger'
